apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  revision: 1-23-0
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
