apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      - name: client
        image: mysql:8.0
        command: ["sleep", "infinity"]
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
