apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  revision: ${istio_label}
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
    pilot:
      k8s:
        env:
          - name: PILOT_FILTER_GATEWAY_CLUSTER_CONFIG
            value: "true"
          - name: PILOT_HTTP10
            value: "true"
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod-${istio_label}
        - apiVersion: autoscaling/v1
          kind: HorizontalPodAutoscaler
          name: istiod-${istio_label}
          patches:
          - path: spec.minReplicas
            value: 1
          - path: spec.maxReplicas
            value: 1
  values:
    global:
      variant: debug
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network2
